# Generated by Django 4.2.1 on 2023-05-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.CharField(max_length=250, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=50, verbose_name='Ответ')),
            ],
        ),
    ]
